[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm_anchor = "DeE6ezmZAt87b9bjfp63xwFZEypFCysn5nLebhSR9ZwX"

[programs.devnet]
amm_anchor = "DeE6ezmZAt87b9bjfp63xwFZEypFCysn5nLebhSR9ZwX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
